[2023-06-24 00:00:01,320] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-23T00:00:00+00:00 [queued]>
[2023-06-24 00:00:01,361] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-23T00:00:00+00:00 [queued]>
[2023-06-24 00:00:01,363] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 00:00:01,364] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2023-06-24 00:00:01,365] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 00:00:01,398] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2023-06-23T00:00:00+00:00
[2023-06-24 00:00:01,406] {standard_task_runner.py:52} INFO - Started process 15328 to run task
[2023-06-24 00:00:01,415] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2023-06-23T00:00:00+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpfu7amivo', '--error-file', '/tmp/tmpxq8te5j9']
[2023-06-24 00:00:01,417] {standard_task_runner.py:77} INFO - Job 35: Subtask task_zero
[2023-06-24 00:00:01,522] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2023-06-23T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-06-24 00:00:01,666] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T00:00:00+00:00
[2023-06-24 00:00:01,673] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-24 00:00:01,677] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2023-06-24 00:00:01,697] {subprocess.py:75} INFO - Output:
[2023-06-24 00:00:07,430] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-24 00:00:08,191] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.2)
[2023-06-24 00:00:08,220] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2023-06-24 00:00:35,245] {subprocess.py:83} INFO - Command exited with return code 0
[2023-06-24 00:00:35,315] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20230623T000000, start_date=20230624T000001, end_date=20230624T000035
[2023-06-24 00:00:35,406] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-24 00:00:35,482] {local_task_job.py:151} INFO - Task exited with return code 0
